pipeline {
    agent any

    environment {
        PROJECT_NAME = "simpleweb_v2"
        BASE_DIR     = "/opt/projects"
        PROJECT_DIR  = "${BASE_DIR}/${PROJECT_NAME}"
        NGINX_DIR    = "/var/www/html"
    }

    stages {

        stage('Setup Permissions') {
            steps {
                sh '''
                    sudo mkdir -p $BASE_DIR
                    sudo chown -R jenkins:jenkins $BASE_DIR
                '''
            }
        }

        stage('Clean Old Code') {
            steps {
                sh '''
                    rm -rf $PROJECT_DIR
                '''
            }
        }

        stage('Clone Code') {
            steps {
                sh '''
                    git clone https://github.com/vijayqadevkraft/webapplication-repo.git $PROJECT_DIR
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    sudo cp $PROJECT_DIR/simpleweb/index.html $NGINX_DIR/
                '''
            }
        }

        stage('Reload Nginx') {
            steps {
                sh '''
                    sudo systemctl reload nginx
                '''
            }
        }
    }
}
