name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 Dev Server
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

          script: |
            echo "🚀 Starting DEV deployment..."

            cd /home/ubuntu

            if [ ! -d "webapplication" ]; then
              git clone https://github.com/vijayqadevkraft/webapplication.git
            fi

            cd webapplication

            git pull origin dev

            cd app/backend

            npm install

            pm2 delete backend-dev || true
            pm2 start server.js --name backend-dev

            cd ../frontend

            sudo rm -rf /var/www/html/*
            sudo cp -r * /var/www/html/

            sudo systemctl restart nginx

            echo "✅ DEV deployment completed"
