name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🚀 Starting deployment..."

            cd /home/ubuntu

            # Clone if not exists
            if [ ! -d "webapplication" ]; then
              git clone https://github.com/vijayqadevkraft/webapplication.git
            fi

            cd webapplication
            git pull origin main

            cd app

            # =========================
            # BACKEND
            # =========================
            echo "⚙️ Backend setup..."
            cd backend

            npm install
            pm2 delete backend || true
            pm2 start server.js --name backend

            cd ..

            # =========================
            # FRONTEND (STATIC)
            # =========================
            echo "🎨 Deploying static frontend..."
            cd frontend

            sudo rm -rf /var/www/html/*
            sudo cp -r * /var/www/html/

            cd ..

            echo "✅ Deployment completed 🎉"
