name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 Production Server
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

          script: |
            echo "🚀 Starting PRODUCTION deployment..."

            cd /home/ubuntu

            if [ ! -d "webapplication" ]; then
              git clone https://github.com/vijayqadevkraft/webapplication.git
            fi

            cd webapplication

            # FIXED GIT COMMANDS
            git fetch origin
            git reset --hard origin/main

            cd app/backend

            npm install

            pm2 delete backend || true
            pm2 start server.js --name backend

            cd ../frontend

            sudo rm -rf /var/www/prod/*
            sudo cp -r * /var/www/prod/

            sudo systemctl restart nginx

            echo "✅ PRODUCTION deployment completed"
